# Generated by Django 6.0.5 on 2026-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('data_contratacao', models.DateField(verbose_name='Data de Contratação')),
            ],
        ),
    ]
