# Generated by Django 6.0.6 on 2026-06-09 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('FUNC', 'Funcionário')], default='FUNC', max_length=10, verbose_name='Tipo de Usuário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
