# Generated by Django 6.0.6 on 2026-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_tipo_usuario_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
