# Generated by Django 6.0.5 on 2026-05-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_entrega', models.TextField(verbose_name='Endereço de Entrega')),
                ('data_envio', models.DateField(verbose_name='Data de Envio')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('status_entrega', models.CharField(choices=[('CADASTRADO', 'Cadastrado'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='CADASTRADO', max_length=20, verbose_name='Status da Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente Responsável')),
                ('funcionario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario', verbose_name='Funcionário Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto Enviado')),
            ],
        ),
    ]
